# Generated by Django 4.2 on 2023-10-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bought',
            field=models.ManyToManyField(blank=True, to='shop.item'),
        ),
    ]
