# Generated by Django 4.2 on 2023-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_profile_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='default.png', max_length=20),
        ),
    ]
